### ISSUE TITLE
Permission denied when running as non-root

### ISSUE THREAD

**Issue by DLmass** [DockOpsLab/composeCD#16]
I get these weird error after adding `user: "${UID}:${GID}"` to the compose file. I want to be able to run it as non-root user. What could be causing this issue?

bulckan  | Starting in 5 seconds...
bulckan  | mkdir: can't create directory '/record': Permission denied
bulckan  | /usr/local/bin/bulckan.sh: line 24: /record/update_count: No such file or directory
bulckan  | /usr/local/bin/bulckan.sh: line 28: /record/last_commit: No such file or directory
bulckan  | /usr/local/bin/bulckan.sh: line 32: /record/last_name: No such file or directory
bulckan  | Updating repository...
bulckan  | remote: Invalid username or password.
bulckan  | fatal: Authentication failed for 'https://github.com/redacted/redacted.git/'
bulckan  | No changes detected in the repository.
bulckan  | Deploying with docker-compose...
bulckan  | grep: repo/homepage//docker-compose.yml: No such file or directory
bulckan  | /usr/local/bin/bulckan.sh: line 108: /record/last_name: No such file or directory
bulckan  | /usr/local/bin/bulckan.sh: line 111: /record/update_count: No such file or directory
bulckan  | /usr/local/bin/bulckan.sh: line 112: /record/last_commit: No such file or directory
bulckan  | /usr/local/bin/bulckan.sh: line 119: /record/last_name: No such file or directory
bulckan  | Compose name: 
bulckan  | Commit deployed: 
bulckan  | Total updates: 
bulckan  |  Container homepage  Running
bulckan  | Sleeping for 3600 seconds...

**Comment by d-vm** [comment]
The problem you face if you do not want to run as root user is that you will have to give permissions to the user configured on docker shocket (/var/run/docker.sock), which in the end is the same as running as root. we can modify the script for you to check the tests I have done but on the host you will have to manually configure the permissions.
Running a container with /var/run/docker.sock as volume is equivalent to having all access on the host.

**Comment by DLmass** [comment]
Thanks for the answer. I will have to look into my docker configuration regarding running it as non-root. 

But regarding the files, I noticed that bulckan changed user and group ownership which resulted in docker user wasn't able to modify the files.

Also does it matter if dockge is used or not?

**Comment by d-vm** [comment]
The script is not prepared for use with a non-root user, at the end of the dockerfile no user other than root was specified, so deploying with a specific user from compose will fail to access the volumes.

We need to make changes to the docekrfile, script and compose to use a non-root user and finally give the non-root user host access to /var/run/docker.sock.

And as I said before, giving a user access to /var/run/docker.sock is like using root, the user will have access to the entire Docker host.

Since deploying the script with or without Docker is not important, you can extract the script from the repository and use it without Docker. if that was the question.

**Comment by DLmass** [comment]
Alright so I deployed the script outside Docker and I am going to use rsync to update the files accordingly. It looks like it's working better now and I have much more control over what it does.

I want to thank you for your advice and help. I'll make sure to check back from time to time to look for updates.
